module.exports = (sequelize, DataTypes) => {
    const ProformaInvoice = sequelize.define(
        "ProformaInvoice",
        {
            Code: {
                type: DataTypes.INTEGER, // Autogenerated, counting
                primaryKey: true,
                autoIncrement: true,
                allowNull: false,
            },
            Date: {
                type: DataTypes.DATEONLY, // Format: YYYY-MM-DD
                allowNull: false,
            },
            PONumber: {
                type: DataTypes.INTEGER, // Foreign key to PurchaseOrder
                references: {
                    model: "PurchaseOrder",
                    key: "Code",
                },
                allowNull: false,
            },
            SupplierId: {
                type: DataTypes.INTEGER, // Autofill from PurchaseOrder
                allowNull: false,
            },
            Notes: {
                type: DataTypes.TEXT, // Free text
                allowNull: true,
            },
        },
        {
            timestamps: true,
            tableName: "ProformaInvoice", // Explicit table name
        }
    );

    ProformaInvoice.associate = (models) => {
        ProformaInvoice.belongsTo(models.PurchaseOrder, {
            foreignKey: "PONumber",
            as: "PurchaseOrder",
        });
        ProformaInvoice.belongsTo(models.Supplier, {
            foreignKey: "SupplierId",
            as: "Supplier",
        });
    };

    return ProformaInvoice;
};
